import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Nav & Common
    dashboard: 'Dashboard',
    newInvoice: 'New Invoice',
    invoiceHistory: 'Invoice History',
    salesReports: 'Sales Reports',
    customers: 'Customers',
    customerLedger: 'Customer Ledger',
    activityLog: 'Activity Log',
    settings: 'Settings',
    signOut: 'Sign Out',
    installApp: 'Install App',
    language: 'Language',
    
    // Dashboard
    businessOverview: 'Business Overview & Financial Command',
    createManageInvoices: 'Create & manage invoices in real time',
    executiveBillingCenter: 'Executive Billing Center',
    realTimeCommand: 'VIJAYA DURGA AGENCIES • Real-time Financial Command',
    dailySummary: 'Daily Summary',
    createInvoice: 'Create Invoice',
    systemActive: 'SYSTEM ACTIVE',
    todaysSales: "Today's Sales",
    thisMonthSales: 'This Month Sales',
    outstandingReceivables: 'Outstanding Receivables',
    totalLifetimeInvoices: 'Total Lifetime Invoices',
    recentInvoices: 'Recent Invoices',
    businessRevenueAnalytics: 'Business Revenue & Analytics',
    revenueCurve: '7-Day Revenue Curve (INR)',
    paymentHealth: 'Payment Health',
    collectionRatio: 'Collection Ratio',
    clearedPaid: 'Cleared (Paid)',
    pendingCredit: 'Pending (Credit)',
    viewAll: 'View All',
    fullSalesReport: 'Full Sales Report →',
    invoiceNo: 'Invoice #',
    date: 'Date',
    companyName: 'Company Name',
    qtyKg: 'Qty (KG)',
    status: 'Status',
    totalAmount: 'Total Amount',
    paid: 'PAID',
    pending: 'PENDING',
    bills: 'bills',
    unpaid: 'unpaid',
    lifetime: 'Lifetime',
    allTime: 'All Time',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    customDate: 'Custom Date',

    // New Bill
    newInvoiceTitle: 'New Invoice',
    step1Customer: '1. Buyer / Customer Info',
    customerName: 'Customer / Company Name',
    customerNamePlaceholder: 'Enter customer name...',
    customerPhone: 'Phone / WhatsApp (Optional)',
    step2Goods: '2. Weighing & Goods Details',
    goodsDescription: 'Description of Goods',
    defaultGoods: 'Fresh Seafood / Prawns Supply',
    weightKg: 'Weight (KG)',
    ratePerKg: 'Rate (₹/KG)',
    addItem: 'Add Item',
    itemAmount: 'Item Amount',
    item: 'Item',
    remove: 'Remove',
    taxDetails: 'Tax Details (CGST / SGST / IGST)',
    cgstRate: 'CGST Rate',
    cgstAmount: 'CGST Amount (₹)',
    sgstRate: 'SGST Rate',
    sgstAmount: 'SGST Amount (₹)',
    igstAmount: 'IGST Amount (₹)',
    step3Payment: '3. Payment & Total',
    paymentStatus: 'Payment Status',
    invoiceDate: 'Invoice Date',
    totalBillAmount: 'Total Bill Amount',
    totalBeforeTax: 'Total (Before Tax)',
    totalTaxAmount: 'Total Tax (CGST + SGST + IGST)',
    grandTotalAfterTax: 'Grand Total (After Tax)',
    itemsIncluded: 'item(s) included',
    saveAndPrint: 'Save & Print (Ctrl + Enter)',
    saveOnly: 'Save Only',
    saving: 'Saving...',
    cancel: 'Cancel',
    back: 'Back',

    // Reports
    salesFinancialReports: 'Sales & Financial Reports',
    reportsSubtitle: 'Comprehensive analytics, tax breakdown, and accounting exports (Admin Exclusive)',
    grossRevenue: 'GROSS REVENUE',
    collectedPaid: 'COLLECTED (PAID)',
    pendingReceivablesTitle: 'PENDING RECEIVABLES',
    avgTicketSize: 'AVG TICKET SIZE',
    taxCollectionBreakdown: 'GST Tax Collection Breakdown',
    taxableValue: 'Taxable Value',
    cgstCollected: 'CGST Collected',
    sgstCollected: 'SGST Collected',
    igstCollected: 'IGST Collected',
    invoicesForSelectedPeriod: 'Invoices for Selected Period',
    invoicesListSubtitle: 'Complete list of tax & commercial invoices generated during this period',
    exportExcel: 'Export Excel (CSV)',
    tallyXml: 'Tally XML',
    noInvoicesFound: 'No invoices found in this date range.',
    viewInvoiceBtn: 'View →',

    // Invoice Detail & Print
    printInvoice: 'Print Invoice',
    downloadPdf: 'Download PDF',
    shareWhatsApp: 'WhatsApp',
    reBill: 'Re-Bill',
    taxInvoiceHeader: 'TAX INVOICE / CASH / CREDIT',
    jaiShreeRam: '॥ జై శ్రీరామ్ ॥',
    proprietor: 'Proprietor',
    bankDetails: 'BANK PAYMENT DETAILS:',
    staff: 'Staff & Labor',
    staffWages: 'Staff & Wages',
    staffWork: 'Staff Attendance & Wages',
    staffSubtitle: 'Track daily labor attendance, processing quantity (KG), rates, and wage accounts',
    amountInWords: 'Amount in Words',
    subtotal: 'Items Subtotal',
    total: 'TOTAL',
    staff: 'Staff & Daily Operations',
    staffWages: 'Staff & Daily Operations',
    staffWork: 'Workers Labor & Daily Operations',
    staffSubtitle: 'Workers labor (KG * rate), Ice blocks used, and Prawn head wastage sales accounts',
    iceBlocks: 'Ice Blocks Tracker',
    iceBlocksUsed: 'Ice Blocks Used',
    ratePerBlock: 'Rate per Block (₹)',
    totalIceCost: 'Total Ice Cost',
    prawnHeadWastage: 'Prawn Head Wastage Sales',
    wastageSold: 'Wastage Sold (KG)',
    totalWastageSales: 'Total Wastage Sales',
    dailyOperations: 'Daily Operations & Net Summary',
    menu: 'Menu',
    grandTotal: 'GRAND TOTAL',
    hsn: 'HSN',
    price: 'PRICE',
    taxRate: 'RATE OF TAX',
    amount: 'AMOUNT',
    sno: 'S.No',
    particulars: 'PARTICULARS',

    // Staff & Operations Extensions
    addWorkEntry: '+ Add Work Entry',
    bulkAttendance: '⚡ Bulk Attendance',
    hideBulkEntry: 'Hide Bulk Entry',
    copyYesterdayTeam: "⚡ Copy Yesterday's Team",
    copyYesterdaySuccess: 'Loaded workers from previous team!',
    attendanceCalendar: 'Attendance Calendar',
    monthlyCalendar: 'Monthly Attendance Calendar',
    workerAccounts: 'Worker Accounts & Ledgers',
    workEntries: 'Daily Work Entries',
    wageSlip: 'Wage Slip',
    printWageSlip: 'Print Wage Slip',
    downloadWageSlip: 'Download Wage Slip',
    workerName: 'Worker Name',
    workerPhone: 'Phone Number',
    quantityKg: 'Quantity (KG)',
    ratePerKg: 'Rate (₹/KG)',
    workType: 'Work Type',
    shift: 'Shift',
    notes: 'Notes',
    presentDays: 'Days Present',
    totalKgProcessed: 'Total KG Processed',
    totalWagesEarned: 'Total Wages Earned',
    averageDailyKg: 'Avg KG / Day',
    selectWorker: 'Select Worker',
    allWorkers: 'All Workers',
    present: 'Present',
    absent: 'Absent',
    filterByWorker: 'Filter by Worker',
    totalWorkers: 'Total Workers',
    todayWorkers: "Today's Workers",
    todayWages: "Today's Wages",
    todayKg: "Today's KG",
    unpaidWages: 'Unpaid Wages',

    // Bill History & Infinite Scroll
    loadMore: 'Load More Invoices',
    showingBills: 'Showing {count} of {total} invoices',
    allLoaded: 'All invoices loaded',
    infiniteScroll: 'Infinite Scroll',

    // Backup Schedule & Data Export
    backupSchedule: 'Automatic Daily Backup',
    backupScheduleDesc: 'Automatically backup your database and send daily reports',
    scheduledTime: 'Scheduled Time (Daily)',
    fullDataExport: 'Full System Data Export',
    fullDataExportDesc: 'Download complete database snapshot (Bills, Customers, Staff, Operations) as JSON backup',
    downloadFullBackup: 'Download Full System Backup (JSON)',
    exportingData: 'Exporting Full Backup...',

    // Push Notifications
    pushNotifications: 'Push Notifications',
    pushNotificationsDesc: 'Get notified for payments, overdue bills, and daily summaries',
    enablePush: 'Enable Browser Notifications',
    notificationsEnabled: 'Notifications Active',
    notificationsBlocked: 'Notifications Blocked in Browser',
    testNotification: 'Send Test Notification',

    // Activity Log
    activityTimeline: 'Activity Timeline',
    liveAuditTrail: 'Live audit trail of all staff, owner & admin actions',
    actionType: 'Action Type',
    userRole: 'User Role',
    allActions: 'All Actions',
    allRoles: 'All Roles',
    adminOnly: 'Admin Only',
    ownerOnly: 'Owner Only',
    staffOnly: 'Staff Only',
    resetFilters: 'Reset Filters',
    totalActionsCount: 'Total: {count} actions',
    noActivityLogs: 'No activity logs found for the selected filters.',

    // Multi-Stream Reports & Sections
    salesAndInvoices: 'Sales Invoices',
    iceBills: 'Ice Purchases',
    workerSalaries: 'Worker Wages',
    wastageIncome: 'Wastage Sales',
    netOperationsSummary: 'Net Operations & Profit',
    customerOutstanding: 'Customer Outstanding',
    normalBillsDesc: 'Sales revenue from customer invoices & GST tax collection',
    iceBillsDesc: 'Ice blocks procurement expenses & plant payments',
    workerSalariesDesc: 'Factory peeling labor, daily wages earned & payment accounts',
    wastageIncomeDesc: 'Revenue earned from selling prawn head and shell waste',
    netProfitDesc: 'Comprehensive net financial profit: (Sales + Wastage) - (Ice + Labor)',
    exportIceReport: 'Export Ice CSV',
    exportWastageReport: 'Export Wastage CSV',
    exportStaffReport: 'Export Wages CSV',
    netFinancialBalance: 'Net Operating Balance',
    totalFactoryCost: 'Total Factory Cost (Ice + Labor)',
    totalDirectIncome: 'Total Direct Income (Sales + Wastage)',

    // Staff dynamic tabs
    workerLaborTitle: 'Worker Labor & Attendance',
    workerLaborSubtitle: 'Daily labor wages (KG * rate), peeling production, and wage accounts',
    iceTrackerTitle: 'Ice Blocks Procurement & Usage',
    iceTrackerSubtitle: 'Record ice blocks supplied to factory, rates per block, supplier tracking, and ice bills',
    wastageTrackerTitle: 'Prawn Head Wastage Sales & Income',
    wastageTrackerSubtitle: 'Track prawn head / shell waste dispatches, rates per KG, buyer details, and sales income',
    workerAccountsTitle: 'Worker Wage Ledgers & Balances',
    workerAccountsSubtitle: 'Consolidated lifetime attendance, total wages earned, payments cleared, and pending balance',
    dailyNetTitle: 'Daily Operational Net Profit & Expenses',
    dailyNetSubtitle: 'Consolidated operational statement: Labor wages + Ice procurement vs Wastage sales revenue',
    attendanceCalendarTitle: 'Monthly Labor Attendance Calendar',
    attendanceCalendarSubtitle: 'Visual day-by-day attendance heat map, daily headcount, and daily processing volume',
    draftSaved: 'Draft Saved',
    clearDraft: 'Clear Draft',
    discardDraftConfirm: 'Clear unsaved draft entries?',
    bulkStaffAttendanceEntry: 'Bulk Staff Attendance Entry',
    bulkStaffSubtitle: 'Quickly record weights and rates for multiple workers on the same date',
    batchWorkDate: 'Batch Work Date',
    addAnotherWorkerRow: '+ Add Another Worker Row',
    totalBatchWorkers: 'Total Batch Workers',
    saveAllWorkers: 'Save All Workers',
    iceFrom: 'Ice From (Supplier)',
    iceTo: 'Ice To (Receiver)',
    iceBlocksCount: 'Blocks',
    ratePerBlockShort: 'Rate (₹)',
    printIceBill: 'Print Ice Bill',
    singleWorkerBill: 'Print Bill',
    workerStatementBill: 'Print Statement',
  },
  te: {
    // Nav & Common
    dashboard: 'డ్యాష్‌బోర్డ్',
    newInvoice: 'కొత్త బిల్లు',
    invoiceHistory: 'బిల్లుల చరిత్ర',
    salesReports: 'సేల్స్ నివేదికలు',
    customers: 'ఖాతాదారులు',
    customerLedger: 'ఖాతా లెడ్జర్',
    activityLog: 'కార్యకలాపాల లాగ్',
    settings: 'సెట్టింగ్స్',
    signOut: 'లాగ్ అవుట్',
    installApp: 'యాప్ ఇన్‌స్టాల్',
    language: 'భాష',

    // Dashboard
    businessOverview: 'వ్యాపార సమీక్ష మరియు అమ్మకాల వివరాలు',
    createManageInvoices: 'ఇన్వాయిస్ బిల్లులు సులభంగా తయారు చేయండి',
    executiveBillingCenter: 'ఎగ్జిక్యూటివ్ బిల్లింగ్ సెంటర్',
    realTimeCommand: 'విజయదుర్గా ఏజెన్సీస్ • రియల్-టైమ్ ఆర్థిక నిర్వహణ',
    dailySummary: 'రోజువారీ నివేదిక',
    createInvoice: '+ కొత్త బిల్లు',
    systemActive: 'సిస్టమ్ యాక్టివ్',
    todaysSales: 'ఈ రోజు అమ్మకాలు',
    thisMonthSales: 'ఈ నెల అమ్మకాలు',
    outstandingReceivables: 'రావలసిన బాకీలు',
    totalLifetimeInvoices: 'మొత్తం ఇన్వాయిస్‌లు',
    recentInvoices: 'ఇటీవలి ఇన్వాయిస్ బిల్లులు',
    businessRevenueAnalytics: 'వ్యాపార ఆదాయం & విశ్లేషణ',
    revenueCurve: '7 రోజుల రాబడి వివరాలు (రూ.)',
    paymentHealth: 'చెల్లింపుల నిష్పత్తి',
    collectionRatio: 'వసూళ్ల శాతం',
    clearedPaid: 'చెల్లించినవి (Paid)',
    pendingCredit: 'బాకీ ఉన్నవి (Credit)',
    viewAll: 'అన్నీ చూడండి',
    fullSalesReport: 'పూర్తి సేల్స్ నివేదిక →',
    invoiceNo: 'బిల్లు నం.',
    date: 'తేదీ',
    companyName: 'కస్టమర్ / కంపెనీ పేరు',
    qtyKg: 'తూకం (కేజీలు)',
    status: 'స్థితి',
    totalAmount: 'మొత్తం సొమ్ము',
    paid: 'చెల్లించబడింది',
    pending: 'బాకీ ఉంది',
    bills: 'బిల్లులు',
    unpaid: 'బాకీ',
    lifetime: 'మొత్తం రికార్డు',
    allTime: 'అన్ని కాలాలు',
    today: 'ఈ రోజు',
    yesterday: 'నిన్న',
    thisWeek: 'ఈ వారం',
    thisMonth: 'ఈ నెల',
    lastMonth: 'గత నెల',
    customDate: 'తేదీ ఎంచుకోండి',

    // New Bill
    newInvoiceTitle: 'కొత్త ఇన్వాయిస్ బిల్లు',
    step1Customer: '1. కొనుగోలుదారు / కస్టమర్ వివరాలు',
    customerName: 'కస్టమర్ / కంపెనీ పేరు',
    customerNamePlaceholder: 'కస్టమర్ పేరు నమోదు చేయండి...',
    customerPhone: 'ఫోన్ / వాట్సాప్ నంబర్ (ఐచ్ఛికం)',
    step2Goods: '2. సరుకు మరియు తూకం వివరాలు',
    goodsDescription: 'సరుకు వివరాలు',
    defaultGoods: 'రొయ్యలు / చేపల సప్లై (Fresh Seafood / Prawns)',
    weightKg: 'తూకం (కేజీలు)',
    ratePerKg: 'ధర (రూ./కేజీ)',
    addItem: '+ కొత్త ఐటమ్ కలపండి',
    itemAmount: 'ఐటమ్ మొత్తం',
    item: 'ఐటమ్',
    remove: 'తొలగించు',
    taxDetails: 'పన్ను వివరాలు (CGST / SGST / IGST)',
    cgstRate: 'CGST శాతం (%)',
    cgstAmount: 'CGST మొత్తం (₹)',
    sgstRate: 'SGST శాతం (%)',
    sgstAmount: 'SGST మొత్తం (₹)',
    igstAmount: 'IGST మొత్తం (₹)',
    step3Payment: '3. చెల్లింపు మరియు మొత్తం బిల్లు',
    paymentStatus: 'చెల్లింపు స్థితి',
    invoiceDate: 'ఇన్వాయిస్ తేదీ',
    totalBillAmount: 'మొత్తం బిల్లు విలువ',
    totalBeforeTax: 'సరుకు మొత్తం (పన్ను లేకుండా - Before Tax)',
    totalTaxAmount: 'మొత్తం GST పన్ను (CGST + SGST + IGST)',
    grandTotalAfterTax: 'మొత్తం బిల్లు (పన్నుతో కలిపి - Grand Total)',
    itemsIncluded: 'ఐటమ్స్ ఉన్నాయి',
    saveAndPrint: 'సేవ్ & ప్రింట్ చేయండి (Ctrl + Enter)',
    saveOnly: 'సేవ్ చేయండి',
    saving: 'సేవ్ అవుతోంది...',
    cancel: 'రద్దు చేయండి',
    back: 'వెనక్కి',

    // Reports
    salesFinancialReports: 'సేల్స్ & ఆర్థిక నివేదికలు',
    reportsSubtitle: 'సమగ్ర విశ్లేషణ, GST పన్ను విభజన మరియు అకౌంటింగ్ ఎగుమతులు (అడ్మిన్ ఎక్స్‌క్లూజివ్)',
    grossRevenue: 'మొత్తం అమ్మకాలు (GROSS REVENUE)',
    collectedPaid: 'వసూలైన మొత్తం (COLLECTED)',
    pendingReceivablesTitle: 'రావలసిన బాకీలు (PENDING)',
    avgTicketSize: 'సగటు బిల్లు విలువ (AVG TICKET)',
    taxCollectionBreakdown: 'GST పన్ను వసూళ్ల విభజన',
    taxableValue: 'పన్ను విధించదగిన విలువ',
    cgstCollected: 'వసూలైన CGST',
    sgstCollected: 'వసూలైన SGST',
    igstCollected: 'వసూలైన IGST',
    invoicesForSelectedPeriod: 'ఎంచుకున్న కాలంలోని ఇన్వాయిస్ బిల్లులు',
    invoicesListSubtitle: 'ఈ కాలంలో జారీ చేసిన పన్ను & కమర్షియల్ ఇన్వాయిస్‌ల పూర్తి జాబితా',
    exportExcel: 'ఎక్సెల్ (CSV) డౌన్‌లోడ్',
    tallyXml: 'టాలీ XML ఎగుమతి',
    noInvoicesFound: 'ఎంచుకున్న కాలంలో ఎటువంటి బిల్లులు లేవు.',
    viewInvoiceBtn: 'బిల్లు చూడండి →',

    // Invoice Detail & Print
    printInvoice: 'బిల్లు ప్రింట్ చేయండి',
    downloadPdf: 'PDF డౌన్‌లోడ్',
    shareWhatsApp: 'వాట్సాప్‌లో పంపండి',
    reBill: 'మళ్లీ బిల్లు చేయండి',
    taxInvoiceHeader: 'TAX INVOICE / CASH / CREDIT',
    jaiShreeRam: '॥ జై శ్రీరామ్ ॥',
    proprietor: 'ప్రొప్రైటర్',
    bankDetails: 'బ్యాంకు చెల్లింపు వివరాలు:',
    staff: 'సిబ్బంది & కార్యకలాపాలు',
    staffWages: 'సిబ్బంది & రోజువారీ ఖర్చులు',
    staffWork: 'కూలీ వేతనాలు & రోజువారీ లెక్కలు',
    staffSubtitle: 'కూలీ వేతనాలు (KG * రేటు), వాడిన ఐస్ బ్లాకులు, మరియు రొయ్య తలల వేస్టేజ్ అమ్మకాల లెక్కలు',
    iceBlocks: 'ఐస్ బ్లాకుల ట్రాకర్',
    iceBlocksUsed: 'వాడిన ఐస్ బ్లాకులు',
    ratePerBlock: 'ఒక్కో బ్లాక్ ధర (₹)',
    totalIceCost: 'మొత్తం ఐస్ ఖర్చు',
    prawnHeadWastage: 'రొయ్య తలల వేస్టేజ్ అమ్మకాలు',
    wastageSold: 'అమ్మిన వేస్టేజ్ (కేజీలు)',
    totalWastageSales: 'మొత్తం వేస్టేజ్ ఆదాయం',
    dailyOperations: 'రోజువారీ నికర లెక్కలు',
    menu: 'మెనూ',
    amountInWords: 'అక్షరాలా మొత్తం',
    subtotal: 'సరుకు మొత్తం',
    total: 'మొత్తం (TOTAL)',
    grandTotal: 'మొత్తం చెల్లించవలసినది (GRAND TOTAL)',
    hsn: 'HSN కోడ్',
    price: 'ధర (రూ.)',
    taxRate: 'పన్ను రేటు',
    amount: 'మొత్తం (రూ.)',
    sno: 'వ.సంఖ్య',
    particulars: 'సరుకు వివరాలు',

    // Staff & Operations Extensions (Telugu)
    addWorkEntry: '+ కూలీ పని నమోదు',
    bulkAttendance: '⚡ బల్క్ హాజరు',
    hideBulkEntry: 'బల్క్ నమోదు దాచండి',
    copyYesterdayTeam: "⚡ నిన్నటి బృందాన్ని తీసుకురండి",
    copyYesterdaySuccess: 'నిన్నటి కార్మికుల వివరాలు లోడ్ అయ్యాయి!',
    attendanceCalendar: 'హాజరు క్యాలెండర్',
    monthlyCalendar: 'నెలవారీ హాజరు క్యాలెండర్',
    workerAccounts: 'కార్మికుల ఖాతా లెడ్జర్లు',
    workEntries: 'రోజువారీ పని రికార్డులు',
    wageSlip: 'వేతన స్లిప్',
    printWageSlip: 'వేతన స్లిప్ ప్రింట్ చేయండి',
    downloadWageSlip: 'వేతన స్లిప్ డౌన్‌లోడ్',
    workerName: 'కార్మికుని పేరు',
    workerPhone: 'ఫోన్ నంబర్',
    quantityKg: 'తూకం (కేజీలు)',
    ratePerKg: 'ధర (రూ./కేజీ)',
    workType: 'పని రకం',
    shift: 'షిఫ్ట్',
    notes: 'గమనికలు',
    presentDays: 'పని చేసిన రోజులు',
    totalKgProcessed: 'మొత్తం తూకం (కేజీలు)',
    totalWagesEarned: 'మొత్తం సంపాదించిన కూలీ',
    averageDailyKg: 'సగటు కేజీలు / రోజు',
    selectWorker: 'కార్మికుడిని ఎంచుకోండి',
    allWorkers: 'అందరూ కార్మికులు',
    present: 'హాజరయ్యారు',
    absent: 'గైర్హాజరు',
    filterByWorker: 'కార్మికుని ప్రకారం ఫిల్టర్',
    totalWorkers: 'మొత్తం కార్మికులు',
    todayWorkers: 'ఈ రోజు కార్మికులు',
    todayWages: 'ఈ రోజు కూలీ',
    todayKg: 'ఈ రోజు కేజీలు',
    unpaidWages: 'చెల్లించాల్సిన కూలీ',

    // Bill History & Infinite Scroll (Telugu)
    loadMore: 'మరిన్ని బిల్లులు చూడండి',
    showingBills: '{total} బిల్లులలో {count} కనిపిస్తున్నాయి',
    allLoaded: 'అన్ని ఇన్వాయిస్‌లు లోడ్ అయ్యాయి',
    infiniteScroll: 'నిరంతర స్క్రోలింగ్',

    // Backup Schedule & Data Export (Telugu)
    backupSchedule: 'ఆటోమేటిక్ రోజువారీ బ్యాకప్',
    backupScheduleDesc: 'మీ వ్యాపార డేటాను ఆటోమేటిక్‌గా బ్యాకప్ చేసి రోజూ నివేదికలను పంపుతుంది',
    scheduledTime: 'రోజువారీ సమయం',
    fullDataExport: 'పూర్తి డేటా ఎగుమతి',
    fullDataExportDesc: 'అన్ని బిల్లులు, కస్టమర్లు, సిబ్బంది మరియు లెక్కల పూర్తి బ్యాకప్ డౌన్‌లోడ్ చేయండి',
    downloadFullBackup: 'పూర్తి సిస్టమ్ బ్యాకప్ డౌన్‌లోడ్ చేయండి (JSON)',
    exportingData: 'డేటా ఎగుమతి అవుతోంది...',

    // Push Notifications (Telugu)
    pushNotifications: 'పుష్ నోటిఫికేషన్‌లు',
    pushNotificationsDesc: 'చెల్లింపులు, బాకీ బిల్లులు మరియు రోజువారీ నివేదికల కోసం హెచ్చరికలు పొందండి',
    enablePush: 'బ్రౌజర్ నోటిఫికేషన్‌లను ప్రారంభించండి',
    notificationsEnabled: 'నోటిఫికేషన్‌లు యాక్టివ్‌గా ఉన్నాయి',
    notificationsBlocked: 'బ్రౌజర్‌లో నోటిఫికేషన్‌లు నిలిపివేయబడ్డాయి',
    testNotification: 'పరీక్ష నోటిఫికేషన్ పంపండి',

    // Activity Log (Telugu)
    activityTimeline: 'కార్యకలాపాల కాలక్రమం',
    liveAuditTrail: 'సిబ్బంది, యజమాని మరియు అడ్మిన్ పనుల లైవ్ ఆడిట్ రికార్డు',
    actionType: 'పని రకం',
    userRole: 'వినియోగదారు హోదా',
    allActions: 'అన్ని పనులు',
    allRoles: 'అన్ని హోదాలు',
    adminOnly: 'అడ్మిన్ మాత్రమే',
    ownerOnly: 'యజమాని మాత్రమే',
    staffOnly: 'సిబ్బంది మాత్రమే',
    resetFilters: 'ఫిల్టర్లు రీసెట్ చేయండి',
    totalActionsCount: 'మొత్తం: {count} పనులు',
    noActivityLogs: 'ఎంచుకున్న ఫిల్టర్లకు ఎటువంటి కార్యకలాపాలు లేవు.',

    // Multi-Stream Reports & Sections (Telugu)
    salesAndInvoices: 'అమ్మకాల ఇన్వాయిస్‌లు',
    iceBills: 'ఐస్ కొనుగోళ్లు',
    workerSalaries: 'కూలీల వేతనాలు',
    wastageIncome: 'వేస్టేజ్ అమ్మకాలు',
    netOperationsSummary: 'నికర వ్యాపార లాభనష్టాలు',
    customerOutstanding: 'ఖాతాదారుల బాకీలు',
    normalBillsDesc: 'కస్టమర్ ఇన్వాయిస్ అమ్మకాలు మరియు GST పన్ను వసూళ్లు',
    iceBillsDesc: 'ఐస్ కొనుగోలు ఖర్చులు మరియు ప్లాంట్ చెల్లింపుల వివరాలు',
    workerSalariesDesc: 'ఫ్యాక్టరీ పీలింగ్ కూలీలు, రోజువారీ వేతనాలు మరియు బ్యాలెన్స్ లెక్కలు',
    wastageIncomeDesc: 'రొయ్య తలల వేస్టేజ్ అమ్మకం ద్వారా వచ్చిన వ్యాపార ఆదాయం',
    netProfitDesc: 'పూర్తి నికర వ్యాపార లాభం: (అమ్మకాలు + వేస్టేజ్) - (ఐస్ + కూలీలు)',
    exportIceReport: 'ఐస్ CSV ఎగుమతి',
    exportWastageReport: 'వేస్టేజ్ CSV ఎగుమతి',
    exportStaffReport: 'కూలీల CSV ఎగుమతి',
    netFinancialBalance: 'నికర నిర్వహణ బ్యాలెన్స్',
    totalFactoryCost: 'మొత్తం ఫ్యాక్టరీ ఖర్చు (ఐస్ + కూలీలు)',
    totalDirectIncome: 'మొత్తం ప్రత్యక్ష ఆదాయం (అమ్మకాలు + వేస్టేజ్)',

    // Staff dynamic tabs (Telugu)
    workerLaborTitle: 'కార్మికుల కూలీ & హాజరు',
    workerLaborSubtitle: 'రోజువారీ కూలీ వేతనాలు (కేజీ * రేటు), పీలింగ్ తూకాలు మరియు చెల్లింపుల లెక్కలు',
    iceTrackerTitle: 'ఐస్ బ్లాకుల కొనుగోలు మరియు వినియోగం',
    iceTrackerSubtitle: 'ఫ్యాక్టరీకి వచ్చిన ఐస్ బ్లాకులు, రేట్లు, ఎవరి నుండి ఎవరికి సరఫరా మరియు బిల్లులు',
    wastageTrackerTitle: 'రొయ్య తలల వేస్టేజ్ అమ్మకాలు & ఆదాయం',
    wastageTrackerSubtitle: 'రొయ్య తలల వేస్టేజ్ ఎగుమతులు, కేజీ రేటు, కొనుగోలుదారులు మరియు ఆదాయ వివరాలు',
    workerAccountsTitle: 'కార్మికుల ఖాతా లెడ్జర్లు & బ్యాలెన్సులు',
    workerAccountsSubtitle: 'కార్మికుల పూర్తి హాజరు, సంపాదించిన కూలీ, ఇచ్చిన చెల్లింపులు మరియు బాకీ బ్యాలెన్స్',
    dailyNetTitle: 'రోజువారీ నికర లాభనష్టాలు & నిర్వహణ ఖర్చులు',
    dailyNetSubtitle: 'ఫ్యాక్టరీ నిర్వహణ సమగ్ర లెక్క: కూలీ వేతనాలు + ఐస్ ఖర్చులు vs వేస్టేజ్ అమ్మకాల ఆదాయం',
    attendanceCalendarTitle: 'నెలవారీ కార్మికుల హాజరు క్యాలెండర్',
    attendanceCalendarSubtitle: 'రోజులవారీ హాజరు విశ్లేషణ, కార్మికుల సంఖ్య మరియు రోజు ప్రాసెసింగ్ వివరాలు',
    draftSaved: 'డ్రాఫ్ట్ భద్రపరచబడింది',
    clearDraft: 'డ్రాఫ్ట్ తొలగించు',
    discardDraftConfirm: 'సేవ్ చేయని డ్రాఫ్ట్ వివరాలను తొలగించాలా?',
    bulkStaffAttendanceEntry: 'బల్క్ సిబ్బంది హాజరు నమోదు',
    bulkStaffSubtitle: 'ఒకే తేదీన ఎక్కువ మంది కార్మికుల తూకాలు మరియు రేట్లు సులభంగా నమోదు చేయండి',
    batchWorkDate: 'పని చేసిన తేదీ',
    addAnotherWorkerRow: '+ మరొక కార్మికుడిని చేర్చండి',
    totalBatchWorkers: 'మొత్తం బ్యాచ్ కార్మికులు',
    saveAllWorkers: 'కార్మికులందరినీ సేవ్ చేయండి',
    iceFrom: 'ఎవరి నుండి (సరఫరాదారు)',
    iceTo: 'ఎవరికి (స్వీకరించేవారు)',
    iceBlocksCount: 'బ్లాకులు',
    ratePerBlockShort: 'రేటు (రూ.)',
    printIceBill: 'ఐస్ బిల్లు ప్రింట్',
    singleWorkerBill: 'బిల్లు ప్రింట్',
    workerStatementBill: 'స్టేట్‌మెంట్ ప్రింట్',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('srsf_lang') || 'en';
  });

  const toggleLang = () => {
    const nextLang = lang === 'en' ? 'te' : 'en';
    setLang(nextLang);
    localStorage.setItem('srsf_lang', nextLang);
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
